### ISSUE TITLE
Add a Security tag

### ISSUE THREAD

**Issue by KINGSABRI** [Florent2/ruby-books#3]
Hi, 
Would you please add a `Security` tag to Rubyfu book since it's a Ruby for hacker book?

If `hacking` category is fine with you, then it will be great too

```
"categories": [
    "free",
    "security",
    "hacking"
  ]
```

Thanks in advanced..

**Comment by Florent2** [comment]
Thanks for the suggestion! Done in e2176b1a33a1dd9a8a6a9fd591e8114d1faa3bfd

**Comment by KINGSABRI** [comment]
Thanks @Florent2
